export default {
    en: [{
        id: 1,
        name: 'Promotion'
    }, {
        id: 2,
        name: 'Music'
    }, {
        id: 3,
        name: 'Game'
    }, {
        id: 4,
        name: 'Daily Life'
    }, {
        id: 5,
        name: 'Entertainment'
    }, {
        id: 6,
        name: 'Lifestyle'
    }, {
        id: 7,
        name: 'Movie'
    }, {
        id: 8,
        name: 'Hit Affair'
    }, {
        id: 9,
        name: 'Cultural'
    }, {
        id: 10,
        name: 'Anime'
    }, {
        id: 11,
        name: 'Sports'
    }, {
        id: 12,
        name: 'Food'
    }, {
        id: 13,
        name: 'Urban Tale'
    }, {
        id: 14,
        name: 'Supernatural'
    }, {
        id: 15,
        name: 'Conspiracy'
    }, {
        id: 16,
        name: 'Travel'
    }],
    zht: [{
        id: 1,
        name: '文宣'
    }, {
        id: 2,
        name: '音樂'
    }, {
        id: 3,
        name: '遊戲'
    }, {
        id: 4,
        name: '日常'
    }, {
        id: 5,
        name: '娛樂'
    }, {
        id: 6,
        name: '生活'
    }, {
        id: 7,
        name: '電影'
    }, {
        id: 8,
        name: '時事'
    }, {
        id: 9,
        name: '文化'
    }, {
        id: 10,
        name: '動漫'
    }, {
        id: 11,
        name: '運動'
    }, {
        id: 12,
        name: '飲食'
    }, {
        id: 13,
        name: '都市傳說'
    }, {
        id: 14,
        name: '靈異'
    }, {
        id: 15,
        name: '陰謀'
    }, {
        id: 16,
        name: '旅遊'
    }]
};
